// The editor's interface text. Pages pass `lang`, and the editor reads every visible string from here.
// Hindi keeps the words people actually use with forms (photo, KB, pixel, upload) in their common form.

export type Lang = "en" | "hi";

const en = {
  steps: ["Add a photo", "Pick the size", "Frame your face", "Download"],
  promises: ["Free", "No sign-up", "No watermark", "Never uploaded"],
  howItWorks: "How it works",
  whatYouGet: "What you get",
  dropHere: "Drop a photo here",
  releaseToLoad: "Release to load your photo",
  fileTypes: "JPG, PNG or WEBP, up to 20 MB",
  choosePhoto: "Choose photo",
  useCamera: "Use camera",
  staysOnDevice: "Your photo stays on this device. Nothing is uploaded.",
  pickSize: "Pick the size",
  changeLater: "You can change it after adding the photo.",
  customSize: "Custom size",
  anyWidthHeight: "Any width × height",
  setInPixels: "Set in pixels",
  anySize: "Any size",
  anySizeUnder: (kb: number) => `Any size · under ${kb} KB`,
  editPhoto: "Edit photo",
  presetsLabel: "Form and ID presets",
  widthLabel: "Width in pixels",
  heightLabel: "Height in pixels",
  lockAspect: "Lock aspect ratio",
  aspectLocked: "Aspect ratio locked",
  aspectUnlocked: "Aspect ratio unlocked",
  stampToggle: "Name and date on photo",
  stampName: "Name",
  stampNamePlaceholder: "As on the form",
  stampDate: "Date of photo",
  stampNote: (percent: number) => `The strip covers the bottom ${percent}% of the photo, so leave room below your chin.`,
  frameFace: "Frame your face",
  aspectLabel: "Aspect ratio",
  free: "Free",
  rotateLeft: "Rotate left 90°",
  rotateRight: "Rotate right 90°",
  rotated: (degrees: number) => `Rotated ${degrees}°`,
  cropAlt: "Uploaded image to crop",
  previewAlt: "Cropped and resized preview",
  download: "Download",
  exportFormat: "Export format",
  maxFileSize: "Max file size",
  minFileSize: "Min file size",
  any: "Any",
  other: "Other",
  none: "None",
  otherLimit: "Other limit in KB",
  tooBig: (kb: number | null, width: number, height: number) => `Too big for ${kb} KB at ${width} × ${height} px.`,
  fewerPixels: "Fewer pixels make a smaller file.",
  tooSmall: (kb: number | null, width: number, height: number) =>
    `Under the ${kb} KB minimum at ${width} × ${height} px.`,
  morePixels: "More pixels make a bigger file.",
  fullQualityMorePixels: "Even at full quality. More pixels make a bigger file.",
  shrinkToFit: "Shrink to fit",
  enlargeToFit: "Enlarge to fit",
  qualitySetTo: "Quality set to",
  toStayBetween: (min: number, max: number) => `to stay between ${min} and ${max} KB.`,
  toStayUnder: (max: number) => `to stay under ${max} KB.`,
  qualityAuto: (max: number) => `Quality is set automatically to stay under ${max} KB.`,
  qualityRaisedTo: "Quality raised to",
  toStayAbove: (min: number) => `to stay above ${min} KB.`,
  quality: "Quality",
  lossless: "Lossless. Switch to JPEG to set a file size limit, or if the form asks for a smaller file.",
  printComesOut: "Your file appears here once the crop is set.",
  fileDimensions: "Dimensions",
  fileFormat: "Format",
  fileSize: "File size",
  downloadFormat: (format: string) => `Download ${format}`,
  share: "Share",
  startOver: "Start over",
  whatsappNote:
    "Apps like WhatsApp recompress photos sent via Share. For full quality, tap Download, then attach the file as a Document in the app instead.",
  dismiss: "Dismiss",
  takePhoto: "Take a photo",
  cameraOn: "Camera on",
  fitHeadShoulders: "Fit your head and shoulders in the frame",
  cancel: "Cancel",
  capture: "Capture photo",
  errors: {
    preview: "Could not generate a preview for this image.",
    cameraUnsupported: "Camera access isn't supported in this browser.",
    cameraDenied: "Couldn't access the camera. Check permissions and try again.",
    fileType: "Unsupported file type. Please upload a JPG, PNG, or WEBP image.",
    fileSize: (size: string, max: string) => `File is too large (${size}). Maximum size is ${max}.`,
    shrink: "Could not resize this image. Try a smaller width and height.",
    enlarge: "Could not resize this image. Try a larger width and height.",
    export: "Export failed. Please try a different image or settings.",
    shareUnsupported: "Direct sharing isn't supported in this browser. Please download and share manually.",
    share: "Sharing failed. Please try downloading instead.",
    unreadable: "This file could not be read as an image.",
  },
};

export type EditorText = typeof en;

const hi: EditorText = {
  steps: ["फ़ोटो जोड़ें", "साइज़ चुनें", "चेहरा फ़्रेम करें", "डाउनलोड"],
  promises: ["फ़्री", "साइन-अप नहीं", "वॉटरमार्क नहीं", "कभी अपलोड नहीं"],
  howItWorks: "कैसे काम करता है",
  whatYouGet: "आपको क्या मिलता है",
  dropHere: "फ़ोटो यहाँ छोड़ें",
  releaseToLoad: "फ़ोटो लोड करने के लिए छोड़ें",
  fileTypes: "JPG, PNG या WEBP, 20 MB तक",
  choosePhoto: "फ़ोटो चुनें",
  useCamera: "कैमरा इस्तेमाल करें",
  staysOnDevice: "आपकी फ़ोटो इसी डिवाइस पर रहती है। कुछ भी अपलोड नहीं होता।",
  pickSize: "साइज़ चुनें",
  changeLater: "फ़ोटो जोड़ने के बाद भी बदल सकते हैं।",
  customSize: "कस्टम साइज़",
  anyWidthHeight: "कोई भी चौड़ाई × ऊँचाई",
  setInPixels: "पिक्सल में तय",
  anySize: "कोई भी साइज़",
  anySizeUnder: (kb) => `कोई भी साइज़ · ${kb} KB से कम`,
  editPhoto: "फ़ोटो एडिट करें",
  presetsLabel: "फ़ॉर्म और ID प्रीसेट",
  widthLabel: "चौड़ाई (पिक्सल)",
  heightLabel: "ऊँचाई (पिक्सल)",
  lockAspect: "अनुपात लॉक करें",
  aspectLocked: "अनुपात लॉक है",
  aspectUnlocked: "अनुपात अनलॉक है",
  stampToggle: "फ़ोटो पर नाम और तारीख़",
  stampName: "नाम",
  stampNamePlaceholder: "जैसा फ़ॉर्म में है",
  stampDate: "फ़ोटो की तारीख़",
  stampNote: (percent) => `पट्टी फ़ोटो का नीचे का ${percent}% हिस्सा ढकती है, इसलिए ठुड्डी के नीचे जगह छोड़ें।`,
  frameFace: "चेहरा फ़्रेम करें",
  aspectLabel: "अनुपात",
  free: "फ़्री",
  rotateLeft: "बाएँ 90° घुमाएँ",
  rotateRight: "दाएँ 90° घुमाएँ",
  rotated: (degrees) => `${degrees}° घुमाया`,
  cropAlt: "क्रॉप करने के लिए जोड़ी गई फ़ोटो",
  previewAlt: "क्रॉप और रीसाइज़ की गई फ़ोटो का प्रीव्यू",
  download: "डाउनलोड",
  exportFormat: "फ़ाइल फ़ॉर्मेट",
  maxFileSize: "अधिकतम फ़ाइल साइज़",
  minFileSize: "न्यूनतम फ़ाइल साइज़",
  any: "कोई भी",
  other: "दूसरा",
  none: "कोई नहीं",
  otherLimit: "दूसरी लिमिट, KB में",
  tooBig: (kb, width, height) => `${width} × ${height} px पर ${kb} KB से बड़ी है।`,
  fewerPixels: "कम पिक्सल से फ़ाइल छोटी होती है।",
  tooSmall: (kb, width, height) => `${width} × ${height} px पर ${kb} KB की न्यूनतम सीमा से छोटी है।`,
  morePixels: "ज़्यादा पिक्सल से फ़ाइल बड़ी होती है।",
  fullQualityMorePixels: "पूरी क्वालिटी पर भी। ज़्यादा पिक्सल से फ़ाइल बड़ी होती है।",
  shrinkToFit: "छोटा करके फ़िट करें",
  enlargeToFit: "बड़ा करके फ़िट करें",
  qualitySetTo: "क्वालिटी",
  toStayBetween: (min, max) => `पर सेट है, ताकि फ़ाइल ${min} से ${max} KB के बीच रहे।`,
  toStayUnder: (max) => `पर सेट है, ताकि फ़ाइल ${max} KB से कम रहे।`,
  qualityAuto: (max) => `क्वालिटी अपने-आप सेट होती है, ताकि फ़ाइल ${max} KB से कम रहे।`,
  qualityRaisedTo: "क्वालिटी बढ़ाकर",
  toStayAbove: (min) => `की गई, ताकि फ़ाइल ${min} KB से ऊपर रहे।`,
  quality: "क्वालिटी",
  lossless: "लॉसलेस। फ़ाइल साइज़ की लिमिट लगानी हो या फ़ॉर्म छोटी फ़ाइल माँगे, तो JPEG चुनें।",
  printComesOut: "क्रॉप सेट होते ही आपकी फ़ाइल यहाँ दिखेगी।",
  fileDimensions: "साइज़",
  fileFormat: "फ़ॉर्मेट",
  fileSize: "फ़ाइल साइज़",
  downloadFormat: (format) => `${format} डाउनलोड करें`,
  share: "शेयर",
  startOver: "फिर से शुरू करें",
  whatsappNote:
    "WhatsApp जैसे ऐप Share से भेजी फ़ोटो को फिर से कंप्रेस करते हैं। पूरी क्वालिटी के लिए Download दबाएँ, फिर ऐप में फ़ाइल को Document की तरह भेजें।",
  dismiss: "बंद करें",
  takePhoto: "फ़ोटो खींचें",
  cameraOn: "कैमरा चालू",
  fitHeadShoulders: "सिर और कंधे फ़्रेम के अंदर रखें",
  cancel: "रद्द करें",
  capture: "फ़ोटो खींचें",
  errors: {
    preview: "इस फ़ोटो का प्रीव्यू नहीं बन सका।",
    cameraUnsupported: "इस ब्राउज़र में कैमरा इस्तेमाल नहीं हो सकता।",
    cameraDenied: "कैमरा नहीं खुल सका। परमिशन देखें और फिर कोशिश करें।",
    fileType: "यह फ़ाइल टाइप नहीं चलेगा। JPG, PNG या WEBP फ़ोटो जोड़ें।",
    fileSize: (size, max) => `फ़ाइल बहुत बड़ी है (${size})। अधिकतम साइज़ ${max} है।`,
    shrink: "फ़ोटो रीसाइज़ नहीं हो सकी। कम चौड़ाई और ऊँचाई आज़माएँ।",
    enlarge: "फ़ोटो रीसाइज़ नहीं हो सकी। ज़्यादा चौड़ाई और ऊँचाई आज़माएँ।",
    export: "फ़ाइल नहीं बन सकी। दूसरी फ़ोटो या सेटिंग आज़माएँ।",
    shareUnsupported: "इस ब्राउज़र में सीधे शेयर नहीं होता। डाउनलोड करके शेयर करें।",
    share: "शेयर नहीं हो सका। डाउनलोड करके देखें।",
    unreadable: "यह फ़ाइल फ़ोटो की तरह नहीं पढ़ी जा सकी।",
  },
};

export const EDITOR_TEXT: Record<Lang, EditorText> = { en, hi };
